

images ='C:\Users\jessa\Downloads\example_good_quality_retinal_images';  
files=dir(fullfile(images,'\*.png*'));

output_xls = "\stats.xlsx";

n1=numel(files);

header = ["picture" ...
    ...
    "mean_R" "mean_G" "mean_B" ...
    "std_R" "std_G" "std_B" ...
    "skew_R" "skew_G" "skew_B" ...
    ...
    "mean_L" "mean_A" "mean_B2" ...
    "std_L" "std_A" "std_B2" ...
    "skew_L" "skew_A" "skew_B2" ...
    ...
    "mean_L_norm" "mean_A_norm" "mean_B2_norm" ...
    "std_L_norm" "std_A_norm" "std_B2_norm" ...
    "skew_L_norm" "skew_A_norm" "skew_B2_norm"];

writematrix(header, images+output_xls);


for idx = 1:n1
    im = files(idx).name;
    disp(strcat("working on: ",im))
    inImg = imread(fullfile(images,im));
    
    [X, inx] = ROI(inImg);
    
    X3 = reshape(X,[],3);
    
    Lab = rgb2lab(X);
    
    Lab3 = reshape(Lab,[],3);
    
    mn = min(min(Lab));
    mx = max(max(Lab));
    mx = mx(:); mn = mn(:);
    
    Lab_norm(:,:,1) = (Lab(:,:,1)-mn(1))/(mx(1)-mn(1));
    Lab_norm(:,:,2) = (Lab(:,:,2)-mn(2))/(mx(2)-mn(2));
    Lab_norm(:,:,3) = (Lab(:,:,3)-mn(3))/(mx(3)-mn(3));
    
    Lab_norm3 = reshape(Lab_norm, [], 3);
    
    
    stats = {im,...
        mean(X3(inx,:)),...
        std(double(X3(inx,:))),...
        skewness(double(X3(inx,:))),...
        ...
        mean(Lab3(inx,:)),...
        std(Lab3(inx,:)),...
        skewness(Lab3(inx,:)),...
        ...
        mean(Lab_norm3(inx,:)),...
        std(Lab_norm3(inx,:)),...
        skewness(Lab_norm3(inx,:))
        };
    
    writecell(stats, images+output_xls, 'WriteMode', 'append');
end

disp("Done!!");
